import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import styles from './page.module.css';
import Nav from './common/nav';
import Footer from './common/footer';


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className={styles.main}>
          <Nav></Nav>

          <div className={styles.center}>
            {children}
          </div>
    
          <Footer></Footer>
        </main>
      </body>
    </html>
  )
}
